use "../STD/STD.e"

static Flags{
    long KEYWORD_COMPONENT = 1
	long UNDEFINED_COMPONENT = 2
	long PAREHTHESIS_COMPONENT = 4
	long END_COMPONENT = 8
	long STRING_COMPONENT = 16
	long NUMBER_COMPONENT = 32
	long COMMENT_COMPONENT = 64
	long OPERATOR_COMPONENT = 128
	long TEXT_COMPONENT = 256
	long END_OF_DIRECTIVE_CHANGING_FILE = 512
	long TEMPLATE_COMPONENT = 1024
	long NUMERICAL_TYPE_COMPONENT= 2048
}